export {
  register,
  registerAdmin,
  login,
  getCurrentUser,
  logout,
  fetchBlogs,
  fetchBlog,
  fetchForumPosts,
  fetchForumPost,
  fetchForumComments,
  createComment,
  votePost,
  removeVote,
  createForumPost,
  uploadPostImage,
  fetchCafeteriaMenus,
  fetchUserProfile,
  updateUserProfile,
  uploadProfilePhoto,
} from './mockApi';
